services:
  postgres:
    image: "bitnami/postgresql"
    container_name: "fsw-barber-postgres"
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=barbershop
